### ISSUE TITLE
Workflow (aka branching model)

### ISSUE THREAD

**Issue by valberg** [kbhff/eggplant#15]
We need to discuss how which kind of branching model we wish to use.

I suggest a very simple one summarized in this gist:

https://gist.github.com/jbenet/ee6c9ac48068889b0912

**Comment by sepow** [comment]
This seems like a reasonable way to do it. +1

**Comment by benjaoming** [comment]
:+1:

**Comment by pawciobiel** [comment]
I'm always quite septic when someone is trying to tell me "do this, don't do that".

> git config --global branch.autosetuprebase always

wat?!? please... 

The impression I got is that the author tell us to use "--no-ff". Well I'm sorry but If I will have a branch with one/two commits in it I won't. Also, If one wants to have a fork and do PR from it than I really can't see what could be inappropriate in that.

Let's be less evangelic about things. This is an open source project.

I think knowing git book and github help page, the one about flows, there is one right(?), is good enough.
I'm sorry but let's face it, this isn't a gnome or kernel code project. How many pull requests we had since the project has started(?)

Let's just use common sense, collaborate, comment be lean and agile, talk nicely to each other, read docs and it all will be just fine, I promise.

I vote :-1:

**Comment by mtoftum** [comment]
I'm with valberg on this one. Nice and simple setup.
I don't agree with the "Let's be less evangelic about things. This is an open source project" argument. 
For something opensource it's even nicer to have a common well described way of doing things to make contributions simpler and arguments over form less likely.

**Comment by benjaoming** [comment]
This model is actually a very simple one with lots of freedom! I like it!

**Comment by benjaoming** [comment]
I opened up PR #31 which contains a guide, CONTRIBUTING.rst (scooped from the pypackage cookiecutter... which may have scooped it from somewhere else).

I suggest that we put the info about workflow there.

I'm sympathetic about why @pawciobiel had to divert a bit from this workflow during sprints in the early stages, but if we can stick to this in the future, it'd be great!

**Comment by benjaoming** [comment]
Look! The workflow decision is reflected in the docs, especially in this section:

http://eggplant.readthedocs.org/en/latest/contributing.html#get-started
